name: test template versions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        uses: docker://python:3.12.0
      - run: pip install poetry cookiecutter
